# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8-pose keypoints/pose estimation model. For Usage examples see https://docs.ultralytics.com/tasks/pose

# Parameters
nc: 11 # number of classes
kpt_shape: [17, 3] # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
scales: # model compound scaling constants, i.e. 'model=yolov8n-pose-cspnext.yaml' will call yolov8-pose-cspnext.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.375, 0.167, 384]
  s: [0.33, 0.50, 512]
  m: [0.67, 0.75, 768]
  l: [1.00, 1.00, 1024]

# CSPNeXt backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, STEM, [64]] # 0-P1/2
  # CSPNeXt blocks
  - [-1, 3, CSPNeXtBlocks, [128]] # 1-P2/4 
  - [-1, 6, CSPNeXtBlocks, [256]] # 2-P3/8
  - [-1, 6, CSPNeXtBlocks, [512]] # 3-P4/16
  - [-1, 3, CSPNeXtBlocks, [1024, False, True]] # 4-P5/32

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]] # 5
  - [[-1, 3], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 7

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 2], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 10 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 7], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 13 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 4], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2f, [1024]] # 16 (P5/32-large)

  - [[10, 13, 16], 1, Pose, [nc, kpt_shape]] # Pose(P3, P4, P5)
