# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8-pose keypoints/pose estimation model. For Usage examples see https://docs.ultralytics.com/tasks/pose

# Parameters
nc: 50 # number of classes
kpt_shape: [17, 3] # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
scales: # model compound scaling constants, i.e. 'model=yolov8n-pose-cspnext.yaml' will call yolov8-pose-cspnext.yaml with scale 'n'
  #  [depth, width, max_channels]
  n: [0.33, 0.25, 1024]
  s: [0.33, 0.50, 1024]
  m: [0.67, 0.75, 768]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.25, 512]

# CSPNeXt backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, STEM, [64]] # 0-P1/2
  # CSPNeXt blocks
  - [-1, 1, Conv, [128, 3, 2, 1]] # 1-P2/4
  - [-1, 3, CSPNeXtBlock, [128, True, False, True]] # 2-P2/4
  - [-1, 1, Conv, [256, 3, 2, 1]] # 3-P3/8
  - [-1, 6, CSPNeXtBlock, [256, True, False, True]] # 4-P3/8
  - [-1, 1, Conv, [512, 3, 2, 1]] # 5-P4/16
  - [-1, 6, CSPNeXtBlock, [512, True, False, True]] # 6-P4/16
  - [-1, 1, Conv, [1024, 3, 2, 1]] # 7-P5/32
  - [-1, 3, CSPNeXtBlock, [1024, False, True, True]] # 8-P5/32

# Hybrid Encoder
head:
  - [-1, 1, Conv, [256, 1, 1, None, 1, 1, False]] # 9
  - [-1, 1, AIFI, [1024, 8]]
  - [-1, 1, Conv, [256, 1, 1]] # 11

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [6, 1, Conv, [256, 1, 1, None, 1, 1, False]] # 13
  - [[-2, -1], 1, Concat, [1]]
  - [-1, 3, RepC3, [256]] # 15
  - [-1, 1, Conv, [256, 1, 1]] # 16

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [4, 1, Conv, [256, 1, 1, None, 1, 1, False]] # 18
  - [[-2, -1], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, RepC3, [256]] # X3 (20), fpn_blocks.1

  - [-1, 1, Conv, [256, 3, 2]] # 21, downsample_convs.0
  - [[-1, 16], 1, Concat, [1]] # cat Y4
  - [-1, 3, RepC3, [256]] # F4 (23), pan_blocks.0

  - [-1, 1, Conv, [256, 3, 2]] # 24, downsample_convs.1
  - [[-1, 11], 1, Concat, [1]] # cat Y5
  - [-1, 3, RepC3, [256]] # F5 (26), pan_blocks.1

  - [[20, 23, 26], 1, Pose, [nc, kpt_shape]] # Pose(P3, P4, P5)
