# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8-pose keypoints/pose estimation model. For Usage examples see https://docs.ultralytics.com/tasks/pose

# Parameters
nc: 1 # number of classes
kpt_shape: [35, 3] # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
scales: # model compound scaling constants, i.e. 'model=yolov8n-pose-cspnext.yaml' will call yolov8-pose-cspnext.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]
  s: [0.33, 0.50, 1024]
  m: [0.67, 0.75, 768]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.25, 512]

# CSPNeXt backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, SPIUpResolution, [3]] # 0-P1/2
  - [-1, 1, STEM, [64]] # 1-P1/2
  # CSPNeXt blocks
  - [-1, 1, Conv, [128, 3, 2, 1]] # 2-P2/4
  - [-1, 3, CSPNeXtBlock, [128, True, False, True]] # 3-P2/4
  - [-1, 1, Conv, [256, 3, 2, 1]] # 4-P3/8
  - [-1, 6, CSPNeXtBlock, [256, True, False, True]] # 5-P3/8
  - [-1, 1, Conv, [512, 3, 2, 1]] # 6-P4/16
  - [-1, 6, CSPNeXtBlock, [512, True, False, True]] # 7-P4/16
  - [-1, 1, Conv, [1024, 3, 2, 1]] # 8-P5/32
  - [-1, 3, CSPNeXtBlock, [1024, False, True, True]] # 9-P5/32

# CSPNeXt head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]] # 10
  - [[-1, 7], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, CSPNeXtBlock, [512]] # 12

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 5], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, CSPNeXtBlock, [256]] # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, CSPNeXtBlock, [512]] # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, CSPNeXtBlock, [1024]] # 21 (P5/32-large)

  - [[15, 16, 21], 1, Pose, [nc, kpt_shape]] # Pose(P3, P4, P5)
